Desabilitar botão do microModal após POST
perdedora/nicochan pull request #2
Opened 2024-09-20 17:19 UTC by gabagoolboy

Depois de clicar em "Submit", tem um delay entre a resposta do servidor e o cliente, o que o usuário pode clicar em enviar duas vezes pensando que não foi enviado. 
Esse commit desabilita o botão após o trigger submit.

2024-09-20 17:20 UTC, gabagoolboy commented
Identação saiu cagada ainda, foda-se.

2024-09-20 21:42 UTC, perdedora requested changes
Só altere o que está comentado. Obrigada.

2024-09-20 21:42 UTC, perdedora commented on js/microModal.js
> +		form.querySelector('input[name="report"]').setAttribute('disabled', 'disabled');
Troque para `input[type="submit"]` para englobar o template de delete.

2024-09-21 12:51 UTC, perdedora approved these changes

2024-09-21 12:52 UTC, merged